// This will be my layer for accessing other layers and special functions
// I customize it in keymaps.c, so everything is defaulted to nothing here

#define CONTROL_ESC  KC_NO
#define CONTROL_1    KC_F1
#define CONTROL_2    KC_F2
#define CONTROL_3    KC_F3
#define CONTROL_4    KC_F4
#define CONTROL_5    KC_F5
#define CONTROL_6    KC_F6
#define CONTROL_7    KC_F7
#define CONTROL_8    KC_F8
#define CONTROL_9    KC_F9
#define CONTROL_0    KC_F10
#define CONTROL_MI   KC_F11
#define CONTROL_EQ   KC_F12
#define CONTROL_BSP  KC_DELETE

#define CONTROL_TAB  KC_NO
#define CONTROL_Q    RGB_TOG
#define CONTROL_W    KC_NO
#define CONTROL_E    KC_MEDIA_EJECT
#define CONTROL_R    KC_NO
#define CONTROL_T    KC_NO
#define CONTROL_Y    LAUNCH_YOUTUBE
#define CONTROL_U    QK_DYNAMIC_MACRO_RECORD_START_1
#define CONTROL_I    QK_DYNAMIC_MACRO_RECORD_START_2
#define CONTROL_O    DEBUG_DATA
#define CONTROL_P    KC_NO
#define CONTROL_LB   KC_BRIGHTNESS_DOWN
#define CONTROL_RB   KC_BRIGHTNESS_UP
#define CONTROL_BSL  KC_NO

#define CONTROL_CAP  KC_CAPS_LOCK
#define CONTROL_A    KC_NO
#define CONTROL_S    QK_DYNAMIC_MACRO_RECORD_STOP
#define CONTROL_D    QK_DEBUG_TOGGLE
#define CONTROL_F    KC_NO
#define CONTROL_G    KC_NO
#define CONTROL_H    KC_NO
#define CONTROL_J    QK_DYNAMIC_MACRO_PLAY_1
#define CONTROL_K    QK_DYNAMIC_MACRO_PLAY_2
#define CONTROL_L    KC_NO
#define CONTROL_SC   KC_NO
#define CONTROL_QT   KC_NO
#define CONTROL_ENT  NUMPAD_TIL_ENTER

#define CONTROL_LSH  QK_CAPS_WORD_TOGGLE
#define CONTROL_Z    KC_NO
#define CONTROL_X    KC_NO
#define CONTROL_C    KC_NO
#define CONTROL_V    TOGGLE_VIM
#define CONTROL_B    KC_NO
#define CONTROL_N    ENABLE_NUMPAD
#define CONTROL_M    LAUNCH_YOUTUBE_MUSIC
#define CONTROL_CM   KC_NO
#define CONTROL_DT   KC_NO
#define CONTROL_SL   KC_NO
#define CONTROL_RSH  KC_MUTE

#define CONTROL_LCTL QK_DYNAMIC_MACRO_PLAY_1
#define CONTROL_LGUI DISABLE_MAC
#define CONTROL_LALT ENABLE_MAC
#define CONTROL_SP   KC_MEDIA_PLAY_PAUSE
#define CONTROL_RALT QK_BOOTLOADER // BlackBox
#define CONTROL_RCTL KC_NO

#define CONTROL_AUP  KC_AUDIO_VOL_UP
#define CONTROL_AL   KC_MEDIA_REWIND
#define CONTROL_ADN  KC_AUDIO_VOL_DOWN
#define CONTROL_AR   KC_MEDIA_FAST_FORWARD

#define CONTROL_HOM  KC_MISSION_CONTROL
#define CONTROL_END  KC_LAUNCHPAD
#define CONTROL_PUP  KC_MEDIA_PREV_TRACK
#define CONTROL_PDN  KC_MEDIA_NEXT_TRACK
