#define MAC_ESC  KC_TRANSPARENT
#define MAC_1    KC_TRANSPARENT
#define MAC_2    KC_TRANSPARENT
#define MAC_3    KC_TRANSPARENT
#define MAC_4    KC_TRANSPARENT
#define MAC_5    KC_TRANSPARENT
#define MAC_6    KC_TRANSPARENT
#define MAC_7    KC_TRANSPARENT
#define MAC_8    KC_TRANSPARENT
#define MAC_9    KC_TRANSPARENT
#define MAC_0    KC_TRANSPARENT
#define MAC_MI   KC_TRANSPARENT
#define MAC_EQ   KC_TRANSPARENT
#define MAC_BSP  KC_TRANSPARENT

#define MAC_TAB  KC_TRANSPARENT
#define MAC_Q    KC_TRANSPARENT
#define MAC_W    KC_TRANSPARENT
#define MAC_E    KC_TRANSPARENT
#define MAC_R    KC_TRANSPARENT
#define MAC_T    KC_TRANSPARENT
#define MAC_Y    KC_TRANSPARENT
#define MAC_U    KC_TRANSPARENT
#define MAC_I    KC_TRANSPARENT
#define MAC_O    KC_TRANSPARENT
#define MAC_P    KC_TRANSPARENT
#define MAC_LB   KC_TRANSPARENT
#define MAC_RB   KC_TRANSPARENT
#define MAC_BSL  KC_TRANSPARENT

#define MAC_CAP  KC_TRANSPARENT
#define MAC_A    KC_TRANSPARENT
#define MAC_S    KC_TRANSPARENT
#define MAC_D    KC_TRANSPARENT
#define MAC_F    KC_TRANSPARENT
#define MAC_G    KC_TRANSPARENT
#define MAC_H    KC_TRANSPARENT
#define MAC_J    KC_TRANSPARENT
#define MAC_K    KC_TRANSPARENT
#define MAC_L    KC_TRANSPARENT
#define MAC_SC   KC_TRANSPARENT
#define MAC_QT   KC_TRANSPARENT
#define MAC_ENT  KC_TRANSPARENT

#define MAC_LSH  KC_TRANSPARENT
#define MAC_Z    KC_TRANSPARENT
#define MAC_X    KC_TRANSPARENT
#define MAC_C    KC_TRANSPARENT
#define MAC_V    KC_TRANSPARENT
#define MAC_B    KC_TRANSPARENT
#define MAC_N    KC_TRANSPARENT
#define MAC_M    KC_TRANSPARENT
#define MAC_CM   KC_TRANSPARENT
#define MAC_DT   KC_TRANSPARENT
#define MAC_SL   KC_TRANSPARENT
#define MAC_RSH  KC_TRANSPARENT

#define MAC_LCTL KC_TRANSPARENT
#define MAC_LGUI KC_LEFT_ALT     // swap alt/gui
#define MAC_LALT KC_LEFT_GUI     // swap alt/gui
#define MAC_SP   KC_TRANSPARENT
#define MAC_RALT KC_RIGHT_GUI    // to right gui
#define MAC_RCTL KC_TRANSPARENT

#define MAC_AUP  KC_TRANSPARENT
#define MAC_AL   KC_TRANSPARENT
#define MAC_ADN  KC_TRANSPARENT
#define MAC_AR   KC_TRANSPARENT

#define MAC_HOM  KC_TRANSPARENT
#define MAC_END  KC_TRANSPARENT
#define MAC_PUP  KC_TRANSPARENT
#define MAC_PDN  KC_TRANSPARENT
