#define VIM_ESC  KC_TRANSPARENT
#define VIM_1    KC_TRANSPARENT
#define VIM_2    KC_TRANSPARENT
#define VIM_3    KC_TRANSPARENT
#define VIM_4    KC_TRANSPARENT
#define VIM_5    KC_TRANSPARENT
#define VIM_6    KC_TRANSPARENT
#define VIM_7    KC_TRANSPARENT
#define VIM_8    KC_TRANSPARENT
#define VIM_9    KC_TRANSPARENT
#define VIM_0    KC_TRANSPARENT
#define VIM_MI   KC_TRANSPARENT
#define VIM_EQ   KC_TRANSPARENT
#define VIM_BSP  KC_TRANSPARENT

#define VIM_TAB  KC_TRANSPARENT
#define VIM_Q    KC_TRANSPARENT
#define VIM_W    KC_TRANSPARENT
#define VIM_E    KC_TRANSPARENT
#define VIM_R    KC_TRANSPARENT
#define VIM_T    KC_TRANSPARENT
#define VIM_Y    KC_TRANSPARENT
#define VIM_U    KC_TRANSPARENT
#define VIM_I    KC_TRANSPARENT
#define VIM_O    KC_TRANSPARENT
#define VIM_P    KC_TRANSPARENT
#define VIM_LB   KC_TRANSPARENT
#define VIM_RB   KC_TRANSPARENT
#define VIM_BSL  KC_TRANSPARENT

#define VIM_CAP  KC_ESC           // NOTE: ESCAPE
#define VIM_A    KC_TRANSPARENT
#define VIM_S    KC_TRANSPARENT
#define VIM_D    KC_TRANSPARENT
#define VIM_F    KC_TRANSPARENT
#define VIM_G    KC_TRANSPARENT
#define VIM_H    KC_TRANSPARENT
#define VIM_J    KC_TRANSPARENT
#define VIM_K    KC_TRANSPARENT
#define VIM_L    KC_TRANSPARENT
#define VIM_SC   KC_TRANSPARENT
#define VIM_QT   KC_TRANSPARENT
#define VIM_ENT  KC_TRANSPARENT

#define VIM_LSH  KC_TRANSPARENT
#define VIM_Z    KC_TRANSPARENT
#define VIM_X    KC_TRANSPARENT
#define VIM_C    KC_TRANSPARENT
#define VIM_V    KC_TRANSPARENT
#define VIM_B    KC_TRANSPARENT
#define VIM_N    KC_TRANSPARENT
#define VIM_M    KC_TRANSPARENT
#define VIM_CM   KC_TRANSPARENT
#define VIM_DT   KC_TRANSPARENT
#define VIM_SL   KC_TRANSPARENT
#define VIM_RSH  KC_TRANSPARENT

#define VIM_LCTL KC_TRANSPARENT
#define VIM_LGUI KC_TRANSPARENT
#define VIM_LALT KC_TRANSPARENT
#define VIM_SP   KC_TRANSPARENT
#define VIM_RALT KC_TRANSPARENT
#define VIM_RCTL KC_TRANSPARENT

#define VIM_AUP  KC_TRANSPARENT
#define VIM_AL   KC_TRANSPARENT
#define VIM_ADN  KC_TRANSPARENT
#define VIM_AR   KC_TRANSPARENT

#define VIM_HOM  KC_TRANSPARENT
#define VIM_END  KC_TRANSPARENT
#define VIM_PUP  KC_TRANSPARENT
#define VIM_PDN  KC_TRANSPARENT
